name: Build and Deploy Nuxt Application

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Passen Sie die Version an Ihre Nuxt.js-Kompatibilität an.

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt.js project
        run: npm run build

      - name: Check Deployment Conditions and Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          if [ -z "${{ secrets.PROD_PATH }}" ] && [ -z "${{ secrets.PROD_PASSWORD }}" ] && [ -z "${{ secrets.PROD_USER }}" ] && [ -z "${{ secrets.PROD_HOST }}" ]; then
            echo "Error: Any of PROD_HOST, PROD_USER, PROD_PASSWORD, PROD_PATH is not defined for production deployment."
            exit 1
          fi
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.PROD_SFTP || secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          protocol: ${{ secrets.PROD_SFTP && 'sftp' || 'ftp' }}
          port: ${{ secrets.PROD_SFTP && '22' || '21' }}
          local-dir: ./dist/
          server-dir: ${{ secrets.PROD_PATH }}
          security: strict
          state-name: state-production.json

      - name: Check Deployment Conditions and Deploy to Staging
        if: github.ref != 'refs/heads/main'
        run: |
          if [ -z "${{ secrets.STAGE_PATH }}" ] && [ -z "${{ secrets.STAGE_PASSWORD }}" ] && [ -z "${{ secrets.STAGE_USER }}" ] && [ -z "${{ secrets.STAGE_HOST }}" ]; then
            echo "Error: Any of STAGE_HOST, STAGE_USER, STAGE_PASSWORD, STAGE_PATH is not defined for staging deployment."
            exit 1
          fi
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.STAGE_SFTP || secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_USER }}
          password: ${{ secrets.STAGE_PASSWORD }}
          protocol: ${{ secrets.STAGE_SFTP && 'sftp' || 'ftp' }}
          port: ${{ secrets.STAGE_SFTP && '22' || '21' }}
          local-dir: ./dist/
          server-dir: ${{ secrets.STAGE_PATH }}
          security: strict
          state-name: state-staging.json
