name: Build and Deploy Nuxt Application

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt.js project
        run: npm run build

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' && (secrets.PROD_SFTP != '' || secrets.PROD_HOST != '')
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.PROD_SFTP || secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          protocol: ${{ secrets.PROD_SFTP && 'sftp' || 'ftp' }}
          port: ${{ secrets.PROD_SFTP && '22' || '21' }}
          local-dir: ./dist/ # Standard-Verzeichnis für den Output von Nuxt.js
          server-dir: ${{ secrets.PROD_PATH }}
          security: strict
          state-name: state-production.json

      - name: Deploy to Staging
        if: github.ref != 'refs/heads/main' && (secrets.STAGE_SFTP != '' || secrets.STAGE_HOST != '')
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.STAGE_SFTP || secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_USER }}
          password: ${{ secrets.STAGE_PASSWORD }}
          protocol: ${{ secrets.STAGE_SFTP && 'sftp' || 'ftp' }}
          port: ${{ secrets.STAGE_SFTP && '22' || '21' }}
          local-dir: ./dist/ # Standard-Verzeichnis für den Output von Nuxt.js
          server-dir: ${{ secrets.STAGE_PATH }}
          security: strict
          state-name: state-staging.json
